steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "$BRANCH_NAME"
- id: 'install checkov'
  name: 'python:3.9'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
       
        pip install --upgrade pip
        pip install checkov
        checkov --version
        checkov -d . --output json --output-file checkov_report.json --quiet || (echo "Checkov scan failed!" && exit 1) 

- id: 'tf init'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |

      terraform init -reconfigure
- id: 'tf plan'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform plan

- id: 'tf apply or destroy'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      terraform $_TFACTION -auto-approve

    
#timeout = 6100s
logsBucket: 'terraformbackendmysqlapplication'
options:
  logging: GCS_ONLY


